/*
 * generated by Xtext 2.37.0
 */
package org.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DungeonDSLStandaloneSetup extends DungeonDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new DungeonDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
