/*
 * generated by Xtext 2.37.0
 */
package org.xtext.tests

import com.google.inject.Inject

import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.xtext.dungeonDSL.Dungeon

@ExtendWith(InjectionExtension)
@InjectWith(DungeonDSLInjectorProvider)
class DungeonDSLParsingTest {
	@Inject
	ParseHelper<Dungeon> parseHelper

	val validDungeon = '''
		Dungeon MyDungeon {
			theme = "Dark"
			lvl = 1
			Floor FirstFloor {
				Room A {
					size = SMALL
					type = COMBAT
					connections = [B]
				}
				Room B {
					size = MEDIUM
					type = TREASURE
					connections = [A]
				}
			}
		}
	'''

	/* Test if a valid dungeon model parses without any errors */
	@Test
	def void parseValidDungeon() {
		println("Testing valid model: checking that a complete dungeon with two rooms parses correctly.")
		val model = parseHelper.parse(validDungeon)
		Assertions.assertNotNull(model)
		Assertions.assertTrue(model.eResource.errors.empty,
			'''Unexpected errors: «model.eResource.errors.join(", ")»''')
		println("Success: Valid model parsed with no errors. \n")
	}
	
	/* Similar to the above, checks if a minimal correct model parses successfully */
	@Test
	def void loadModel() {
		println("Testing basic model: verifying that a simple dungeon with rooms can be loaded.")
	  	val result = parseHelper.parse('''
	  	Dungeon Example {
	   		theme = "Adventure"
	   		lvl = 1
	   		Floor Start {
	   			Room A {
	   				size = SMALL
	  				type = TREASURE
	  				connections = [B]
	 			}
	 			Room B {
	 				size = MEDIUM
	 				type = TREASURE
	 				connections = [A]
				}
			}
	}
  			''')
  		Assertions.assertNotNull(result)
  		val errors = result.eResource.errors
  		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		println("Success: Minimal dungeon model parsed without issues. \n")
	}

	
	// Check if parsing fails when invalid values are used for enum/number fields
	@Test
	def void parseFailsOnBadTrap() {
		println("Testing invalid model: using a trap with wrong boolean and out-of-range triggerChance.")
		val model = parseHelper.parse('''
			Dungeon Broken {
				theme = "Cursed"
				lvl = 2
				Floor Main {
					Room R {
						size = LARGE
						type = BOSS
						connections = []
						Trap T {
							trigger = stepOn
							disarmable = maybe
							triggerChance = 101
						}
					}
				}
			}
		''')

		Assertions.assertFalse(model.eResource.errors.empty,
			"Expected parser errors due to invalid boolean or number value")
		println("Success: Invalid values triggered expected parser errors. \n")
	}
	
	/* Test if parser catches negative numbers where only positives should be allowed */
	@Test
	def void parseFailsOnNegativeTrapChance() {
		println("Testing invalid model: setting a negative triggerChance value for a trap.")
		val model = parseHelper.parse('''
			Dungeon NegativeTrap {
				theme = "Dark"
				lvl = 3
				Floor LevelOne {
					Room TrapRoom {
						size = MEDIUM
						type = COMBAT
						connections = []
						Trap Explosive {
							trigger = stepOn
							disarmable = true
							triggerChance = -1
						}
					}
				}
			}
		''')
		Assertions.assertFalse(model.eResource.errors.empty,
			"Expected parser or validation error due to negative triggerChance")
		println("Success: Negative triggerChance correctly caused a parsing error. \n")
	}
	
	 
	/* Checks that cyclic room connections (room A to B and B to A) don’t cause parsing errors */
	@Test
	def void detectCyclicRoomConnections() {
		println("Testing room connectivity: parsing a model with cyclic room connections (A <-> B).")
  		val model = parseHelper.parse('''
			Dungeon LoopDungeon {
				theme = "Loop"
				lvl = 999
				Floor F1 {
					Room A {
						size = MEDIUM
						type = COMBAT
						connections = [B]
					}
					Room B {
						size = MEDIUM
						type = TREASURE
						connections = [A]
					}
		}
	}
	''')
		/* 
		Checks that cyclic room connections (room A <-> B <-> A) dont cause parsing errors.
		This doesnt validate that cycles arent allowed and only confirms the parser can handle them.
		We could later extend this with validation logic to detect unwanted cycles.
		For now, we just assert no errors to test the base case
		*/
	  Assertions.assertTrue(model.eResource.errors.empty, "Unexpected errors in the model")
	  println("Success: Cyclic room connections parsed successfully. \n")
	}
	
	

	/* Checks if properties of parsed Room objects are correctly set */
	@Test
	def void testRoomStructure() {
		println("Testing room structure: checking that parsed room has correct name and no connections.")
		val model = parseHelper.parse('''
	    Dungeon TestD {
	      theme = "Dark"
	      lvl = 1
	      Floor A {
	        Room R1 {
	          size = SMALL
	          type = COMBAT
	          connections = []
	        }
	      }
	    }
	  ''')
	  val room = model.floors.head.rooms.head
	  Assertions.assertEquals("R1", room.name)
	  Assertions.assertEquals(0, room.connections.size)
	  println("Success: Room name and structure parsed as expected. \n")
	}
	
	

	/* Testing valid cross-reference between rooms: Room A connects to Room B. */
	@Test
	def void roomCanReferenceOtherRoom() {
		println("Testing valid cross-reference between rooms: Room A connects to Room B.")
		val model = parseHelper.parse('''
			Dungeon MyDungeon {
				theme = "Dark"
				lvl = 5
				Floor F1 {
					Room A {
						size = SMALL
						type = COMBAT
						connections = [B]
					}
					Room B {
						size = SMALL
						type = COMBAT
						connections = [A]
					}
				}
			}
		''')
		Assertions.assertTrue(model.eResource.errors.empty, "Expected no errors for valid cross-referencing.")
		println("Success: Valid cross-reference between rooms parsed correctly. \n")
	}

	

	

	/* Testing NPC reference: NPC B uses NPC A's health value within the same room. */
	@Test
	def void npcCanReferenceOtherNPCHealth() {
		println("Testing NPC reference: NPC B uses NPC A's health value within the same room.")
		val model = parseHelper.parse('''
			Dungeon RefTest {
				theme = "Dark"
				lvl = 1
				Floor Main {
					Room R {
						size = MEDIUM
						type = COMBAT
						connections = []
						NPC A {
							behaviour = NEUTRAL
							type = NORMAL
							health = 10
						}
						NPC B {
							behaviour = NEUTRAL
							type = NORMAL
							health = A
						}
					}
				}
			}
		''')
		Assertions.assertTrue(model.eResource.errors.empty, "Expected valid health reference to another NPC.")
		println("Success: NPC health reference within the same room parsed correctly. \n")
	}

	
	
	/* Testing expression evaluation: NPC health uses arithmetic expression with dungeon level. */
	@Test
	def void npcHealthCanUseArithmetic() {
		println("Testing expression evaluation: NPC health uses arithmetic expression with dungeon level.")
		val model = parseHelper.parse('''
			Dungeon MathTest {
				theme = "Dark"
				lvl = 10
				Floor Main {
					Room Room1 {
						size = SMALL
						type = COMBAT
						connections = []
						NPC Goblin {
							behaviour = AGGRESSIVE
							type = ENEMY
							health = lvl * 2 + 5
						}
					}
				}
			}
		''')
		Assertions.assertTrue(model.eResource.errors.empty, "Expected valid arithmetic using lvl reference.")
		println("Success: NPC health arithmetic with lvl parsed correctly. \n")
	}
	
	
}