/*
 * generated by Xtext 2.37.0
 */
package org.xtext.validation;

import org.eclipse.xtext.validation.Check;
import org.xtext.dungeonDSL.Trap;
import static org.xtext.dungeonDSL.DungeonDSLPackage.Literals;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class DungeonDSLValidator extends AbstractDungeonDSLValidator {
	
	public static final String TRIGGER_CHANCE_OUT_OF_RANGE = "trigger_chance_out_of_range";

	@Check
	public void checkTrapTriggerChance(Trap trap) {
	    int chance = trap.getTriggerChance();
	    if (chance < 0 || chance > 100) {
	        error(
	            "Trigger chance must be between 0 and 100",
	            Literals.TRAP__TRIGGER_CHANCE,
	            TRIGGER_CHANCE_OUT_OF_RANGE
	        );
	    }
	}
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					DungeonDSLPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
}
