/*
 * generated by Xtext 2.37.0
 */
package org.xtext.validation;

import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.validation.Check;
import org.xtext.dungeonDSL.Trap;
import static org.xtext.dungeonDSL.DungeonDSLPackage.Literals;
import org.xtext.dungeonDSL.NPCReference;
import org.xtext.dungeonDSL.NPC;
import org.xtext.dungeonDSL.Room;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class DungeonDSLValidator extends AbstractDungeonDSLValidator {
	
	public static final String TRIGGER_CHANCE_OUT_OF_RANGE = "trigger_chance_out_of_range";

	@Check
	public void checkTrapTriggerChance(Trap trap) {
	    int chance = trap.getTriggerChance();
	    if (chance < 0 || chance > 100) {
	        error(
	            "Trigger chance must be between 0 and 100",
	            Literals.TRAP__TRIGGER_CHANCE,
	            TRIGGER_CHANCE_OUT_OF_RANGE
	        );
	    }
	}

	@Check
	public void checkNPCReferenceIsInSameRoom(NPCReference ref) {
	    NPC target = ref.getNpc();
	    if (target == null) return; // Unresolved references are already caught by the framework

	    Room currentRoom = EcoreUtil2.getContainerOfType(ref, Room.class);
	    if (currentRoom == null) return;

	    if (!currentRoom.getNpcs().contains(target)) {
	        error(
	            "NPC " + target.getName() + " is not visible in this room",
	            Literals.NPC_REFERENCE__NPC
	        );
	    }
	}	

	@Check
	public void checkRoomDoesNotConnectToSelf(Room room) {
	    for (Room conn : room.getConnections()) {
	        if (conn == room) {
	            error("A room cannot connect to itself", Literals.ROOM__CONNECTIONS);
	        }
	    }
	}	
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					DungeonDSLPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
}
